language: objective-c

branches:
  only:
    - master

xcode_project: Permission.xcodeproj
xcode_scheme: PermissionTests
osx_image: xcode11.2
xcode_sdk: iphonesimulator12.4

script:
  - xcodebuild test -project Permission.xcodeproj -scheme PermissionTests -destination "platform=iOS Simulator,name=iPhone Xs"
